[build-system]
requires = ["setuptools>=78", "setuptools-scm[toml]>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "trasyn"
authors = [{ name = "Christoph Fleckenstein (based on work from Tianyi Hao)", email = "c.fleckenstein@parityqc.com" }]
description = "synch: a unitary synthesis method for fault-tolerant quantum computing using gates from the Clifford hierarchy"
readme = "README.md"
requires-python = ">=3.10"
keywords = ["quantum computing"]
license = "MIT"
license-files = ["LICENSE"]
dependencies = ["numpy>=1.26.4", "psutil>=6", "sympy", "tqdm", "matplotlib", "scipy"]
dynamic = ["version"]

[project.optional-dependencies]
cupy-cuda11 = ["cupy-cuda11x>=13.3.0"]
cupy-cuda13 = ["cupyx>=13.3.0"]
qiskit = ["qiskit>=1.2.4"]

[project.urls]
"Repository" = "https://github.com/ctfle/synch"

[tool.setuptools]
packages = ["trasyn"]

[tool.black]
line-length = 99 # override black's default line-length
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | venv
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
# make it compatible with black
profile = "black"
